# Generated by Django 6.0.7 on 2026-07-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="项目简介")),
                ("github_url", models.URLField(verbose_name="GitHub 地址")),
                (
                    "display_date",
                    models.CharField(
                        blank=True,
                        help_text="例如：2026.06",
                        max_length=20,
                        verbose_name="展示日期",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="可填写 Emoji，例如 📦",
                        max_length=20,
                        verbose_name="图标",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="是否显示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["order", "-display_date", "name"],
            },
        ),
    ]
