# Generated by Django 6.0.7 on 2026-07-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ("order", "-display_date", "name"),
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="可填写 Emoji，例如：📦",
                max_length=20,
                verbose_name="图标",
            ),
        ),
    ]
