# Generated by Django 6.0.7 on 2026-07-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_project_options_alter_project_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="一言内容")),
                (
                    "author",
                    models.CharField(blank=True, max_length=120, verbose_name="作者"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="例如：出自《人间失格》",
                        max_length=200,
                        verbose_name="出处",
                    ),
                ),
                ("published_at", models.DateTimeField(verbose_name="展示日期")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="数字越小越靠前；日期相同时生效",
                        verbose_name="排序",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="是否显示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "一言",
                "verbose_name_plural": "一言",
                "ordering": ("-published_at", "order", "-created_at"),
            },
        ),
    ]
