# Generated by Django 6.0.7 on 2026-07-15 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_note_thought"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="专栏名称")),
                (
                    "slug",
                    models.SlugField(
                        help_text="建议使用英文、小写字母和短横线",
                        max_length=60,
                        unique=True,
                        verbose_name="URL 标识",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="专栏简介")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="可以填写一个 Emoji，例如：🍵",
                        max_length=20,
                        verbose_name="图标",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "手记专栏",
                "verbose_name_plural": "手记专栏",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="blog.notecollection",
                verbose_name="所属专栏",
            ),
        ),
    ]
