# Generated by Django 6.0.7 on 2026-07-15 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_notecollection_note_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(
                        max_length=220, unique=True, verbose_name="URL 标识"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(blank=True, max_length=400, verbose_name="摘要"),
                ),
                ("content", models.TextField(blank=True, verbose_name="正文")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="memories/%Y/%m/",
                        verbose_name="图片",
                    ),
                ),
                (
                    "happened_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="这段回忆实际发生的时间。",
                        verbose_name="发生时间",
                    ),
                ),
                (
                    "is_bookmarked",
                    models.BooleanField(default=False, verbose_name="重点回忆"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=20,
                        verbose_name="发布状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "回忆",
                "verbose_name_plural": "回忆",
                "ordering": ["-happened_at"],
            },
        ),
    ]
