# Generated by Django 6.0.7 on 2026-07-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="thought",
            name="comment_count",
            field=models.PositiveIntegerField(default=0, verbose_name="评论数"),
        ),
        migrations.AddField(
            model_name="thought",
            name="favorite_count",
            field=models.PositiveIntegerField(default=0, verbose_name="收藏数"),
        ),
        migrations.AddField(
            model_name="thought",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="喜欢数"),
        ),
        migrations.AddField(
            model_name="thought",
            name="source_description",
            field=models.TextField(blank=True, verbose_name="外部内容简介"),
        ),
        migrations.AddField(
            model_name="thought",
            name="source_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="thoughts/sources/%Y/%m/",
                verbose_name="外部内容封面",
            ),
        ),
        migrations.AddField(
            model_name="thought",
            name="source_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="外部内容标题"
            ),
        ),
        migrations.AddField(
            model_name="thought",
            name="source_url",
            field=models.URLField(blank=True, verbose_name="外部链接"),
        ),
        migrations.AddField(
            model_name="thought",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="标题"),
        ),
        migrations.AddField(
            model_name="thought",
            name="topic",
            field=models.CharField(
                blank=True,
                help_text="例如：回头看见自己",
                max_length=80,
                verbose_name="话题",
            ),
        ),
        migrations.AlterField(
            model_name="thought",
            name="content",
            field=models.TextField(verbose_name="正文"),
        ),
    ]
